# Generated by Django 4.0.2 on 2022-06-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_book_category_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumb',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
