# Generated by Django 4.0.2 on 2022-06-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='books', to='App.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to='book'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumb',
            field=models.ImageField(null=True, upload_to='category'),
        ),
    ]
