# Generated by Django 4.0.2 on 2022-07-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_book_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
