# Generated by Django 4.0.2 on 2022-07-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ref',
            field=models.CharField(default=1000, max_length=200),
        ),
    ]
