# Generated by Django 4.0.2 on 2022-08-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_book_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ref',
            field=models.CharField(default='1000', max_length=200),
        ),
    ]
