# Generated by Django 4.0.2 on 2022-08-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paystack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
